cls
..\85s2lvl\85s2lvl.exe BUGGY.85S buggy.lvl > buggy.log
rem ..\85s2lvl\85s2lvl.exe CAVED.85S caved.lvl > caved.log
rem ..\85s2lvl\85s2lvl.exe STARTREK.85S  startrek.lvl > startrek.log
rem ..\85s2lvl\85s2lvl.exe DEEP.85S deep.lvl         > deep.log
..\85s2lvl\85s2lvl.exe STARTRK2.85S startrk2.lvl         > startrk2.log
..\85s2lvl\85s2lvl.exe MRDIG.85S  mrdig.lvl     > mrdig.log
rem ..\85s2lvl\85s2lvl.exe PIT.85S  pit.lvl         > pit.log
..\85s2lvl\85s2lvl.exe ENTRPRZE.85S  entrprze.lvl  > entrprze.log
