..\85s2lvl\85s2lvl.exe PIRATES.85S  PIRATES.LVL  > PIRATES.LOG
..\85s2lvl\85s2lvl.exe POCMAN.85S   POCMAN.LVL   > POCMAN.LOG
..\85s2lvl\85s2lvl.exe RMAZE.85S    RMAZE.LVL    > RMAZE.LOG
..\85s2lvl\85s2lvl.exe ROBOTW.85S   ROBOTW.LVL   > ROBOTW.LOG
..\85s2lvl\85s2lvl.exe SLEVEL.85S   SLEVEL.LVL   > SLEVEL.LOG
pause
..\85s2lvl\85s2lvl.exe SPACE.85S    SPACE.LVL    > SPACE.LOG
..\85s2lvl\85s2lvl.exe TOMB.85S     TOMB.LVL     > TOMB.LOG
..\85s2lvl\85s2lvl.exe TUT.85S      TUT.LVL      > TUT.LOG
..\85s2lvl\85s2lvl.exe WILD.85S     WILD.LVL     > WILD.LOG
rem ..\85s2lvl\85s2lvl.exe Aliens.85s   ALIENS.LVL   > ALIENS.LOG
rem ..\85s2lvl\85s2lvl.exe SPECTRE.85S  SPECTRE.LVL  > SPECTRE.LOG
rem ..\85s2lvl\85s2lvl.exe TBMIND.85S   TBMIND.LVL   > TBMIND.LOG
rem ..\85s2lvl\85s2lvl.exe TBMAZE.85S   TBMAZE.LVL   > TBMAZE.LOG
rem ..\85s2lvl\85s2lvl.exe THIEF.85S    THIEF.LVL    > THIEF.LOG
